sudo: false
language: node_js
node_js:
- '4.2'
- '0.12'
- '0.10'
- '0.8'
deploy:
  provider: npm
  email:
    secure: "ViDTM3fmacQitnhbymu91sf3Jz1gKPwDX0jmDDnBiycelkvj4HQqS2hCPhKtK5LJt1K5y0omJLtlOhCAlvs/0fFk7wDQeflFXbUK40chPH/tjAmCGAYTfKcYPZN90KJ34DnlPCUt53E3hslXe9TZr1Lu8gUSNFhr5mBgoW4NFco="
  api_key:
    secure: "r/8BFbTuMBUqinTdgcW2aOjTVTxsxnXnhNxS1WVg17ZVqoGuJQ7pVvgjmBxLBteoHq44bFbFP0d9Ou5+iQsOCcgPyifNMWOAeLP8jFwrobLRtTXxxwj7WQgYL0RqisSI96Uh/khuFP6HjVuhnVZ+MY++BqKsWlIevWtuGW8bDkg="
  on:
    tags: true
    repo: fvdm/nodejs-dnsimple
    branch: master
